### ISSUE TITLE
Macro litter data out of date

### ISSUE THREAD

**Issue by hammerdirt-analyst** [hammerdirt-analyst/plastock#1]
There is some data missing

**Comment by alexispochelon** [comment]
i add it later this week

**Comment by hammerdirt-analyst** [comment]
There are still some inconsistencies but that could be due to changes made while we incorporating the old data. The plastock-iqaasl note book has been revised incorporating the new data:

[plastock-iqaasl](https://github.com/hammerdirt-analyst/plastock/tree/plastock-iqaasl)
