### ISSUE TITLE
Graph macro déchets plage et position

### ISSUE THREAD

**Issue by alexispochelon** [hammerdirt-analyst/plastock#10]
hello
Il y a quelque chose qui me surprend en comparant les comptes moyen par échantillon et comptes moyen par position.
Le 50% des comptes moyen par échantillon est à 0.78 et ceux de plage sèche à 0.40 et ligne d'eau à 0.38. Le 50% de la plage entière (compte moyen par échantillon) devrait donc être compris entre 0.38 et 0.40 il me semble non?
A dispo ce matin par téléphone si besoin d'en discuter!
Merci!

**Comment by alexispochelon** [comment]
oui en effet c'est de la médiane que je parlais... 
Je comprends bien pourquoi la médiane est plus basse que la moyenne. En revanche, il me semble quand même pas logique que la médiane sur la plage entière = médiane ligne d'eau + médiane plage sèche. 
On peut en discuter cet après-midi si tu veux!

**Comment by hammerdirt-analyst** [comment]
ouis!

je viens d'appeler le bureau

A+

**Comment by hammerdirt-analyst** [comment]
Tres bien joué Alexis,

En résumé, les sous-sections ont été ajoutées après la prise en compte des unités/m². Le code est passé de :

`position_totalsd = event_total.groupby([*columns], as_index=False)[value].sum()`

à ceci :

```
bpt = event_total.groupby([*columns], as_index=False).agg({'area': 'sum', 'quantite':'sum'})
bpx = bpt.groupby(["echantillon"], as_index=False).agg({'quantite':'sum', 'area':'sum'})
bpx['p/m²]= bpx.quantite/bpx.area
``` 

La médiane est abaissée, mais surtout le calcul est correct.

Merci!

**Comment by alexispochelon** [comment]
super! merci à toi!
