### ISSUE TITLE
problème avec le calcul d'abondance par plage

### ISSUE THREAD

**Issue by alexispochelon** [hammerdirt-analyst/plastock#5]
Hello,
En regardant le détail pour les macros, il me semble qu'il y a un soucis dans le calcul du nombre d'éléments par mètre de plage. Pour le projet plastock, on différencie la ligne d'eau (zone 1) du reste de la plage (zone 2). La zone 1 correspond à la méthode mise en place pour IQAASL (2m depuis l'eau). A mon sens, le nombre d'élément par mètre de plage devraient donc être calculé par zone et par saison.
Sur cette carte: https://hammerdirt-analyst.github.io/plastock/plastock_iqaasl.html, on à l'impression qu'aux Grangettes on trouve entre 10 et 15 pièces par m alors que selon mes calcul on est à 2 pièce par m. 
Qu'en penses-tu?
Merci!

**Comment by hammerdirt-analyst** [comment]
La largeur de la zone d'enquête n'a pas été spécifiée dans l'IQAASL. Elle dépendait de l'emplacement de la ligne de débris. À certains endroits, elle est très petite, comme à Genève. A d'autres endroits, elle s'étend sur toute la plage car les débris ont été poussés jusqu'au mur de soutènement ou à tout autre obstacle séparant la rive du lac du trottoir (ou autre).

Une explication abrégée des méthodes d'enquête est disponible ici :

[IQAASl collecting data](https://hammerdirt-analyst.github.io/IQAASL-End-0f-Sampling-2021/baselines.html#switzerland-2020)

Cependant, la surface a été enregistrée et mesurée pour chaque échantillon, comme cela a été fait dans Plastock. Nous pouvons donc l'utiliser pour comparer les résultats des deuxs enquettes.

**Comment by alexispochelon** [comment]
ok pour la méthode IQAASL. Par contre j'ai quand même le soucis du nombre d'élément par mètre...

**Comment by hammerdirt-analyst** [comment]
Je suis heureux que vous approuviez la méthode utilisée . Nous ne nous lancerions pas dans une telle aventure sans disposer de références académiques suffisantes. La question que je me pose est la suivante : Où sont les références pour la méthode d'échantillonnage du plastock ? 

Existe-t-il une étude qui utilise le m² ? Cette pratique est-elle d'actualité ? Quelles sont les conditions ? Nous n'avions pas de réponse à ces questions, nous avons donc également mesuré le m²  et nous avons rendu compte de la situation conformément à la pratique en vigueur dans le domaine. 

Si je comprend nous cherchons a comparer les résultats entre les deux études. Les m² semble tout a fait juste. Je ne comprends pas le soucis en ce qui concerne notre travail. 

Si c'est un raisonment philosophique (définition de nombres d'éléments par mètre linéaire de plage) il faut aborder cela avec le JRC et OSPAR! 

[OSPAR beach litter monitoring](https://www.ospar.org/documents?v=7260)
[JRC](https://mcc.jrc.ec.europa.eu/documents/201702074014.pdf)

Page 41 JRC:

_Once a beach is chosen sampling units can be identified. A sampling unit is a fixed section of beach
covering the whole area between the water edges (where possible and safe) or from the strandline to the
back of the beach_

**Comment by alexispochelon** [comment]
Hello,
Je ne remettais pas du tout en cause la méthode utilisée ;-)! Pour la méthode utilisée, comme tu le sais on s'est basée sur celle de IQAASL en séparant juste la plage en deux zones (ligne d'eau/reste de la plage). Le mètre linéaire me parait une bonne unité.
Ma seule interrogation était sur le résultat obtenu en nb de particule/passage/ml (cf doc joint) je t'ai mis mon calcul pour les Grangettes). Je pense qu'une des sources de différence est la séparation en deux zones ou non... 


[20230124micro_macrotransmisRoger.xlsx](https://github.com/hammerdirt-analyst/plastock/files/11136268/20230124micro_macrotransmisRoger.xlsx)

**Comment by hammerdirt-analyst** [comment]
Les stocks d'iqaasl étaient en moyenne plus courts et plus étroits que ceux de plastock.

La comparaison a été effectuée en utilisant les deux mesures. branch iqaasl-plastock
